/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class appointment extends javax.swing.JFrame {

    /**
     * Creates new form appointment
     */
    public appointment() {
        initComponents();
        ca.setVisible(false);
        da.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSLabelImage2 = new rojerusan.RSLabelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new rojeru_san.complementos.RSTableMetro();
        da = new rojerusan.RSButtonMetro();
        ca = new rojerusan.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homebutton.jpg"))); // NOI18N
        rSLabelImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSLabelImage2MouseClicked(evt);
            }
        });
        getContentPane().add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 30));

        jLabel1.setBackground(new java.awt.Color(47, 147, 219));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Appointment");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1100, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Search With Doctor ID");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 200, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 450, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 103, -1, 40));

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DoctorID", "PatientID", "Diagnosis"
            }
        ));
        jtable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 800, 200));

        da.setText("Delete Appointment");
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 160, 40));

        ca.setText("Confirm Appointment");
        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 160, 40));

        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, -1, -1));

        jLabel4.setText(" ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, -1, -1));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/appointment.jpg"))); // NOI18N
        getContentPane().add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSLabelImage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSLabelImage2MouseClicked
        // TODO add your handling code here:
        new doctor().setVisible(true);
        dispose();
    }//GEN-LAST:event_rSLabelImage2MouseClicked

    private void jtable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable1MouseClicked
        // TODO add your handling code here:
        int row=jtable1.getSelectedRow();
        String c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 0);
        jLabel3.setText(c);
                
        String c2 = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 1);
        jLabel4.setText(c2);
        
        ca.setVisible(true);
        da.setVisible(true);
    }//GEN-LAST:event_jtable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

             String did = jTextField1.getText();
            int doc_id = Integer.parseInt(did);
                    DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
        table.setRowCount(0);
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT DoctorId, PatientId, Diagnosis FROM `treatment` WHERE DoctorId = ?;");
                ps.setInt(1, doc_id);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String d = rs.getString("DoctorId");
                    String dd = rs.getString("PatientId");
                    
                    String d2 = rs.getString("Diagnosis");
                    
                    table.addRow(new Object[]{d, dd, d2});
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        // TODO add your handling code here:
        int doc_id = Integer.parseInt(jLabel3.getText());
        int pat_id = Integer.parseInt(jLabel4.getText());
        DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
        table.setRowCount(0);
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("DELETE FROM `treatment` WHERE DoctorId = ? and PatientId = ?;");
                ps.setInt(1, doc_id);
                ps.setInt(2, pat_id);
                ps.executeUpdate();
//                while (rs.next()) {
//                    String d = rs.getString("DoctorId");
//                    String dd = rs.getString("PatientId");
//                    
//                    String d2 = rs.getString("Diagnosis");
//                    
//                    table.addRow(new Object[]{d, dd, d2});
//                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }

//        DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
//        table.setRowCount(0);
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT DoctorId, PatientId, Diagnosis FROM `treatment` WHERE DoctorId = ?;");
                ps.setInt(1, doc_id);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String d = rs.getString("DoctorId");
                    String dd = rs.getString("PatientId");
                    
                    String d2 = rs.getString("Diagnosis");
                    
                    table.addRow(new Object[]{d, dd, d2});
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
    }//GEN-LAST:event_daActionPerformed

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        // TODO add your handling code here:
        int pat_id = Integer.parseInt(jLabel4.getText());
            try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("INSERT INTO `patientbill`(`BillId`, `BillAmount`) VALUES (?,?)");
                ps.setInt(1, pat_id);
                ps.setInt(2, 1200);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error5552");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
                try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("INSERT INTO `servicegiven`(`ServiceId`, `PatientId`, `BillId`) VALUES (?,?,?);");
                ps.setInt(1, 1);
                ps.setInt(2, pat_id);
                ps.setInt(3, pat_id);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error5552");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
    }//GEN-LAST:event_caActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro ca;
    private rojerusan.RSButtonMetro da;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private rojeru_san.complementos.RSTableMetro jtable1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    // End of variables declaration//GEN-END:variables
}
