/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import Connection.myconnection;
import static java.lang.Integer.max;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrator
 */
public class employee extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
    
    
    public employee() {
        initComponents();
        
        
        
        DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
        
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT * FROM `employee` WHERE 1;");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String id = rs.getString("Employeeid");
                    String fst = rs.getString("First_Name");
                    String sr = rs.getString("Sur_Name");
                    String salary = rs.getString("Salary");
                    String supervisorid = rs.getString("Supervisorid");
                    String state = rs.getString("State");
                    String street = rs.getString("Street");
                    String country = rs.getString("Country");
                    
                    
                    table.addRow(new Object[]{id, fst, sr, salary, supervisorid, state, street, country});
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
        
    }
    
    
  
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new rojeru_san.complementos.RSTableMetro();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Select Type");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 100, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 170, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Employee ID");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 100, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("First name");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 100, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse", "Admin", "Other" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Supervisor");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 100, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Sur Name");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 30));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 170, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Salary");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 100, 30));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Appointement Schdule");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 170, 30));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 100, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("State");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 100, 30));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 170, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Country");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 100, 30));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 170, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Street");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 100, 30));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 170, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Specialization");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 30));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 170, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("License_num");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 100, 30));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 170, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 170, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 170, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 200, 30));

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Sur Name", "salary", "supervisor", "State", "Country", "Street"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable1.setRowHeight(30);
        jtable1.setRowMargin(2);
        jtable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 790, 400));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/admin_dashboard.jpg"))); // NOI18N
        getContentPane().add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         String sss=(String) jComboBox1.getSelectedItem();
        if(sss.equals("Doctor")){
               jLabel12.setVisible(true);
               jLabel13.setVisible(true);
               jLabel8.setVisible(true);
               jTextField10.setVisible(true);
               jTextField11.setVisible(true);
               jTextField6.setVisible(true);
               jLabel12.setText("Specialization");
               jLabel13.setText("Licesnse_number");
               jLabel8.setText("Appointment_schedule");
        }
        else if(sss.equals("Nurse")){
                jLabel12.setVisible(true);
               jLabel13.setVisible(true);
               jLabel8.setVisible(false);
               jTextField10.setVisible(true);
               jTextField11.setVisible(true);
               jTextField6.setVisible(false);
               jLabel12.setText("Certification");
               jLabel13.setText("Experience");
                  
            
            
        }
        else if(sss.equals("Admin")){
                jLabel12.setVisible(true);
               jLabel13.setVisible(false);
               jLabel8.setVisible(false);
               jTextField10.setVisible(true);
               jTextField11.setVisible(false);
               jTextField6.setVisible(false);
               jLabel12.setText("Role");
              
        }
        else{
          
                jLabel12.setVisible(false);
               jLabel13.setVisible(false);
               jLabel8.setVisible(false);
               jTextField10.setVisible(false);
               jTextField11.setVisible(false);
               jTextField6.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jtable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable1MouseClicked
        // TODO add your handling code here:
        int row=jtable1.getSelectedRow();
        String c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 0);
        jTextField2.setText(c);
         c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 1);
        jTextField3.setText(c);
         c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 2);
        jTextField4.setText(c);
        c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 3);
        jTextField5.setText(c);
         c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 4);
        jTextField1.setText(c);
        c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 5);
        jTextField7.setText(c);
        c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 6);
        jTextField8.setText(c);
        c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 7);
        jTextField9.setText(c);
        
        
        
        String sid = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 0);
        int iid = Integer.parseInt(sid);
        int flag = 0;
        
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT * FROM `doctor` WHERE DoctorId = ?;");
                ps.setInt(1, iid);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    jComboBox1.setSelectedItem("Doctor");
                    flag = 1;
                    
                    jTextField10.setText(rs.getString("Specialization"));
                    jTextField11.setText(rs.getString("LicenseNumber"));
                    jTextField6.setText(rs.getString("AppointmentSchedule"));
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
        
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT * FROM `nurse` WHERE NurseId = ?;");
                ps.setInt(1, iid);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    jComboBox1.setSelectedItem("Nurse");
                    flag = 1;
                    
                    jTextField10.setText(rs.getString("Certification"));
                    jTextField11.setText(rs.getString("Experience"));
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT * FROM `admin` WHERE AdminId = ?;");
                ps.setInt(1, iid);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    jComboBox1.setSelectedItem("Admin");
                    flag = 1;
                    
                    jTextField10.setText(rs.getString("Role"));
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
        
        if(flag == 0){
            jComboBox1.setSelectedItem("Other");
        }
        
    }//GEN-LAST:event_jtable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jtable1.getSelectedRow();
        String eid = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 0);
        int ieid = Integer.parseInt(eid);
        
        System.out.println(ieid);
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("DELETE FROM employee WHERE EmployeeId = ?;");
                ps.setInt(1, ieid);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error5");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
        
        
        DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
        table.setRowCount(0);
        
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT * FROM `employee` WHERE 1;");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String id = rs.getString("Employeeid");
                    String fst = rs.getString("First_Name");
                    String sr = rs.getString("Sur_Name");
                    String salary = rs.getString("Salary");
                    String supervisorid = rs.getString("Supervisorid");
                    String state = rs.getString("State");
                    String street = rs.getString("Street");
                    String country = rs.getString("Country");
                    
                    
                    table.addRow(new Object[]{id, fst, sr, salary, supervisorid, state, street, country});
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
            String empid = jTextField2.getText();
            String fst = jTextField3.getText();
            String lst = jTextField4.getText();
            String salary = jTextField5.getText();
            int isalary = Integer.parseInt(salary);
            String superid = jTextField1.getText();
            int isuperid = Integer.parseInt(superid);
            String state = jTextField7.getText();
            String country = jTextField8.getText();
            String street = jTextField9.getText();
            int id = 1;
             System.out.println("Error");
            try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT EmployeeId FROM `employee` WHERE 1;");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    id = max(id, rs.getInt("EmployeeId") + 1);
                }
                jTextField2.setText(Integer.toString(id));
            } catch (SQLException ex) {
                System.out.println("Error1");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
           
            
            try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("INSERT INTO `employee`(`EmployeeId`, `First_Name`, `Sur_Name`, `Salary`, `SupervisorId`, `State`, `Street`, `Country`) VALUES (?, ?, ?, ?, ?, ?, ?, ?);");
                ps.setInt(1, id);
                ps.setString(2, fst);
                ps.setString(3, lst);
                ps.setInt(4, isalary);
                ps.setInt(5, isuperid);
                ps.setString(6, state);
                ps.setString(7, street);
                ps.setString(8, country);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error2");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
        
        
        
        
        if(jComboBox1.getSelectedItem().equals("Doctor")){
            
            String spec = jTextField10.getText();
            String lscn = jTextField11.getText();
            int ilscn = Integer.parseInt(lscn);
            String apt = jTextField11.getText();           
            System.out.println(id);
            try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("INSERT INTO `doctor`(`DoctorId`, `Specialization`, `LicenseNumber`, `AppointmentSchedule`) VALUES (?, ?, ?, ?);");
                ps.setInt(1, id);
                ps.setString(2, spec);
                ps.setInt(3, ilscn);
                ps.setString(4, apt);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error3");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
            
        } else if(jComboBox1.getSelectedItem().equals("Nurse")){
            String spec = jTextField10.getText();
            String lscn = jTextField11.getText();          
            System.out.println(id);
            try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("INSERT INTO `nurse`(`NurseId`, `Certification`, `Experience`) VALUES (?, ?, ?);");
                ps.setInt(1, id);
                ps.setString(2, spec);
                ps.setString(3, lscn);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error4");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        } else if(jComboBox1.getSelectedItem().equals("Admin")){
            String spec = jTextField10.getText();         
            System.out.println(id);
            try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("INSERT INTO `admin`(`AdminId`, `Role`) VALUES (?, ?);");
                ps.setInt(1, id);
                ps.setString(2, spec);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error5");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        }
        
        
        
        DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
        table.setRowCount(0);
        
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT * FROM `employee` WHERE 1;");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String id1 = rs.getString("Employeeid");
                    String fst2 = rs.getString("First_Name");
                    String sr3 = rs.getString("Sur_Name");
                    String salary4 = rs.getString("Salary");
                    String supervisorid5 = rs.getString("Supervisorid");
                    String state6 = rs.getString("State");
                    String street7 = rs.getString("Street");
                    String country8 = rs.getString("Country");
                    
                    
                    table.addRow(new Object[]{id1, fst2, sr3, salary4, supervisorid5, state6, street7, country8});
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private rojeru_san.complementos.RSTableMetro jtable1;
    private rojerusan.RSLabelImage rSLabelImage1;
    // End of variables declaration//GEN-END:variables
}
