/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrator
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
    
    
    public Rooms() {
        initComponents();
        
        
        DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
        table.setRowCount(0);
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT `RoomId`, `RoomCost`, `RoomType`, `Building`, `Floor` FROM `room` WHERE 1;");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String id = rs.getString("RoomId");
                    String cst = rs.getString("RoomCost");
                    String tp = rs.getString("RoomType");
                    String bd = rs.getString("Building");
                    String fl = rs.getString("Floor");
                    
                    
                    table.addRow(new Object[]{id, cst, tp, bd, fl});
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
    }
    
    
  
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rfloor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rcost = new javax.swing.JTextField();
        rtype = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbuilding = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new rojeru_san.complementos.RSTableMetro();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Room Type");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 30));

        rfloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfloorActionPerformed(evt);
            }
        });
        getContentPane().add(rfloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Room ID");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 100, 30));
        getContentPane().add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Room Cost");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 100, 30));

        rcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcostActionPerformed(evt);
            }
        });
        getContentPane().add(rcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 30));

        rtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICU", "Normal" }));
        rtype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rtypeMouseClicked(evt);
            }
        });
        rtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtypeActionPerformed(evt);
            }
        });
        getContentPane().add(rtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 170, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Floor");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 100, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Building");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 100, 30));

        rbuilding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuildingActionPerformed(evt);
            }
        });
        getContentPane().add(rbuilding, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 170, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 170, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 200, 30));

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "2000", "ICU", "Anatomy", "2"},
                {"1", "500", "Normal", "Physics", "3"},
                {"2", "1000", "ICU", "Chemistry", "1"},
                {"3", "1000", "ICU", "Chemistry", "2"},
                {"4", "500", "Normal", "Physics", "1"},
                {"5", "1000", "ICU", "Physics", "2"},
                {"6", "500", "Normal", "Anatomy", "1"},
                {"7", "1000", "ICU", "Phsyology", "1"},
                {"8", "500", "NORMAL", "Anatomy", "3"},
                {"9", "1000", "ICU", "Physiology", null}
            },
            new String [] {
                "Room ID", "Room Cost", "Room type", "Building", "Floor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable1.setRowHeight(30);
        jtable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 790, 400));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/room2.jpg"))); // NOI18N
        getContentPane().add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rfloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfloorActionPerformed

    private void rcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcostActionPerformed

    private void rbuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuildingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbuildingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rtypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtypeMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rtypeMouseClicked

    private void rtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtypeActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_rtypeActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jtable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable1MouseClicked
        // TODO add your handling code here:
        int row=jtable1.getSelectedRow();
        String c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 0);
        rid.setText(c);
         c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 1);
        rcost.setText(c);
        
        c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 2);
        rtype.setSelectedItem(c);
         c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 3);
        rbuilding.setText(c);
         c = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 4);
        rfloor.setText(c);
      
        
        
    }//GEN-LAST:event_jtable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jtable1.getSelectedRow();
        String rid = (String) jtable1.getValueAt(jtable1.getSelectedRow() , 0);
        int irid = Integer.parseInt(rid);
        
        System.out.println(irid);
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("DELETE FROM `room` WHERE RoomId = ?;");
                ps.setInt(1, irid);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error5");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
        
        
        DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
        table.setRowCount(0);
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT `RoomId`, `RoomCost`, `RoomType`, `Building`, `Floor` FROM `room` WHERE 1;");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String id = rs.getString("RoomId");
                    String cst = rs.getString("RoomCost");
                    String tp = rs.getString("RoomType");
                    String bd = rs.getString("Building");
                    String fl = rs.getString("Floor");
                    
                    
                    table.addRow(new Object[]{id, cst, tp, bd, fl});
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String roomid = rid.getText();
        int roid = Integer.parseInt(roomid);
        int patid = 6;
        String roomcost = rcost.getText();
        int rcost = Integer.parseInt(roomcost);
        String roomtype = (String) rtype.getSelectedItem();
        String roombuilding = rbuilding.getText();
        String roomfloor = rfloor.getText();
        
        
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("INSERT INTO `room`(`RoomId`, `PatientId`, `RoomCost`, `RoomType`, `Building`, `Floor`) VALUES (?, ?, ?, ?, ?, ?);");
                ps.setInt(1, roid);
                ps.setInt(2, patid);
                ps.setString(3, roomcost);
                ps.setString(4, roomtype);
                ps.setString(5, roombuilding);
                ps.setString(6, roomfloor);;
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println("Error2");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
        
        DefaultTableModel table = (DefaultTableModel)jtable1.getModel();
        table.setRowCount(0);
        try {
                Connection con = (Connection) myconnection3.getConnection();
                PreparedStatement ps;
                ps = con.prepareStatement("SELECT `RoomId`, `RoomCost`, `RoomType`, `Building`, `Floor` FROM `room` WHERE 1;");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    String id = rs.getString("RoomId");
                    String cst = rs.getString("RoomCost");
                    String tp = rs.getString("RoomType");
                    String bd = rs.getString("Building");
                    String fl = rs.getString("Floor");
                    
                    
                    table.addRow(new Object[]{id, cst, tp, bd, fl});
                }
            } catch (SQLException ex) {
                System.out.println("Error");
                //Logger.getLogger(seller_interface.class.getName()).log(Level.SEVERE, String.valueOf(id), ex);
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro jtable1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private javax.swing.JTextField rbuilding;
    private javax.swing.JTextField rcost;
    private javax.swing.JTextField rfloor;
    private javax.swing.JTextField rid;
    private javax.swing.JComboBox<String> rtype;
    // End of variables declaration//GEN-END:variables
}
