/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mahatab;

import Connection.myconnection;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class paitentdetails extends javax.swing.JFrame {

    /**
     * Creates new form PatientDetails
     */
    public paitentdetails() {
        initComponents();
        get_the_id();
    }
    int x = 1;
    void get_the_id()
    {
        
        ResultSet rs;
        try {
            Connection con = (Connection) myconnection4.getConnection();
            PreparedStatement ps;
            ps = con.prepareStatement("select * from patient");
            rs = ps.executeQuery();
            while (rs.next()) {
                x++;
            }
            System.out.print(x);
        } catch (SQLException ex) {
            Logger.getLogger(paitentdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        id.setText(String.valueOf(x));
        id.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        phone = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        stree = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        doctor_id = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        email = new javax.swing.JTextField();
        symtomps = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PATIENT DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 930, 50));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Patient ID : ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 80, 20));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 180, 30));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 180, 30));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, 20));
        jPanel2.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 180, -1));

        stree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streeActionPerformed(evt);
            }
        });
        jPanel2.add(stree, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 180, -1));

        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        jPanel2.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 180, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Country : ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 80, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Street : ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 60, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Address : ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 70, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("State : ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 50, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("E-mail : ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Preferred Doctor : ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Date of Birth :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Gender : ");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 80, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Patient Name : ");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, 20));

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SET APPOINTMENT");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 200, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Phone : ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 80, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Symptoms : ");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 90, 20));

        doctor_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor_idActionPerformed(evt);
            }
        });
        jPanel2.add(doctor_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, 20));
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 180, 20));

        symtomps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symtompsActionPerformed(evt);
            }
        });
        jPanel2.add(symtomps, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 150, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 430, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mahatab/pd.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void streeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streeActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new patient().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        try {
                Object selectedItem =gender.getSelectedItem(); 
                java.sql.Date sqldate = new java.sql.Date(jDateChooser2.getDate().getTime());
                Connection con = (Connection) myconnection4.getConnection();
                PreparedStatement ps;
                String sql = "INSERT INTO patient values(?,?,?,?,?,?,?,?)";
                ps = con.prepareStatement(sql);
                ps.setString(1, id.getText());
                ps.setString(2, name.getText());
                ps.setString(3, sqldate.toString());
                ps.setString(4, selectedItem.toString());
                ps.setString(5, email.getText());
                ps.setString(6, state.getText());
                ps.setString(7, stree.getText());
                ps.setString(8, country.getText());
//                if (ps.executeUpdate() > 0) {
//                    JOptionPane.showMessageDialog(new JFrame(), "Information added", "Dialog",
//                            JOptionPane.ERROR_MESSAGE);
//                }
ps.executeUpdate();
//                name.setText("");
//                email.setText("");
//                state.setText("");
//                country.setText("");
//                stree.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(paitentdetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
                Object selectedItem =gender.getSelectedItem(); 
                java.sql.Date sqldate = new java.sql.Date(jDateChooser2.getDate().getTime());
                Connection con = (Connection) myconnection4.getConnection();
                PreparedStatement ps;
                String sql = "INSERT INTO patientphonenumber values(?,?)";
                ps = con.prepareStatement(sql);
                ps.setString(1, id.getText());
                ps.setInt(2,Integer.parseInt(phone.getText()));
                
//                if (ps.executeUpdate() > 0) {
//                    JOptionPane.showMessageDialog(new JFrame(), "Information added", "Dialog",
//                            JOptionPane.ERROR_MESSAGE);
//               }
ps.executeUpdate();
                
                
            } catch (SQLException ex) {
                Logger.getLogger(paitentdetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
                Object selectedItem =gender.getSelectedItem(); 
                java.sql.Date sqldate = new java.sql.Date(jDateChooser2.getDate().getTime());
                Connection con = (Connection) myconnection4.getConnection();
                PreparedStatement ps;
                String sql = "INSERT INTO disease values(?,?)";
                ps = con.prepareStatement(sql);
                ps.setString(1, id.getText());
                ps.setString(2,doctor_id.getText());
                
//                if (ps.executeUpdate() > 0) {
//                    JOptionPane.showMessageDialog(new JFrame(), "Information added", "Dialog",
//                            JOptionPane.ERROR_MESSAGE);
//               }
ps.executeUpdate();
//                doctor_id.setText("");
//                get_the_id();
            } catch (SQLException ex) {
                Logger.getLogger(paitentdetails.class.getName()).log(Level.SEVERE, null, ex);
            }
                   
                
                
                    try {
                Object selectedItem =gender.getSelectedItem(); 
                java.sql.Date sqldate = new java.sql.Date(jDateChooser2.getDate().getTime());
                Connection con = (Connection) myconnection4.getConnection();
                PreparedStatement ps;
                String sql = "INSERT INTO `treatment`(`DoctorId`, `PatientId`, `Diagnosis`, `Date`) VALUES (?,?,?,?)";
                ps = con.prepareStatement(sql);
//                ps.setInt(1, Integer.parseInt(doctor_id.getText()));
//                 ps.setInt(2, Integer.parseInt(id.getText()));
//                ps.setString(3,symtomps.getText());
//                ps.setString(4, sqldate.toString());
ps.setString(2, id.getText());
ps.setString(1, doctor_id.getText());
ps.setString(3, symtomps.getText());
ps.setString(4, sqldate.toString());
                
//                if (ps.executeUpdate() > 0) {
//                    JOptionPane.showMessageDialog(new JFrame(), "Information added", "Dialog",
//                            JOptionPane.ERROR_MESSAGE);
//                }
ps.executeUpdate();
                name.setText("");
                email.setText("");
                state.setText("");
                country.setText("");
                stree.setText("");
                phone.setText("");
                x = 1;
                get_the_id();

            } catch (SQLException ex) {
                Logger.getLogger(paitentdetails.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void doctor_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctor_idActionPerformed

    private void symtompsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symtompsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symtompsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paitentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paitentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paitentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paitentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paitentdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField country;
    private javax.swing.JTextField doctor_id;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField state;
    private javax.swing.JTextField stree;
    private javax.swing.JTextField symtomps;
    // End of variables declaration//GEN-END:variables
}
